// Generated by scripts/lib/image-pipeline.mjs from public/media/*-case-study/manifest.json.
// Do not edit by hand: re-run the asset scripts instead.

export type CaseStudyMediaEntry = { width: number; height: number; alt: string };

export const CASE_STUDY_MEDIA: Record<string, CaseStudyMediaEntry> = {
	"/media/sano-case-study/sano-figma-card.webp": {
		"width": 2000,
		"height": 308,
		"alt": "The RestaurantCard component in two states: review matched, and review source not attached."
	},
	"/media/sano-case-study/sano-figma-grades.webp": {
		"width": 804,
		"height": 188,
		"alt": "Hand-drawn red grade stamps for A, B, C, Pending, and Not yet graded."
	},
	"/media/sano-case-study/sano-figma-handoff.webp": {
		"width": 2000,
		"height": 1992,
		"alt": "Annotated Sano profile screen with numbered developer notes covering WCAG 2.2 focus visibility, target size, the timeline's text alternative, and data rules."
	},
	"/media/sano-case-study/sano-figma-hero.webp": {
		"width": 2000,
		"height": 1389,
		"alt": "Sano home screen in Figma: the headline \"The grade is on the door. The story isn't.\" with a search bar and a preview card for Lucky Chix showing grade A, a volatile inspection timeline, and reliability 60."
	},
	"/media/sano-case-study/sano-figma-profile.webp": {
		"width": 2000,
		"height": 2646,
		"alt": "Sano restaurant profile for Lucky Chix in Figma: official inspection data first with grade A, then consumer review context kept separate, a plain-language summary, reliability 60, and the inspection timeline."
	},
	"/media/sano-case-study/sano-figma-results.webp": {
		"width": 2000,
		"height": 2321,
		"alt": "Sano search results in Figma: a borough coverage snapshot, then restaurant cards showing each official grade, a reliability score, and Google review context only when a source is matched."
	},
	"/media/sano-case-study/sano-live-home.webp": {
		"width": 2000,
		"height": 1250,
		"alt": "The live Sano home page with the hero headline, search bar, and a product preview for Lucky Chix."
	},
	"/media/sano-case-study/sano-live-profile.webp": {
		"width": 2000,
		"height": 1250,
		"alt": "The live Lucky Chix profile: official inspection data with grade A beside separate Google review context."
	}
};
